# This is a basic workflow to help you get started with Actions

name: leetcodeSync

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Sync
        uses: actions/checkout@v4
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: Solutions
          verbose: true
          commit-header: "[LeetCode Sync]"
